# Generated by Django 5.0 on 2024-01-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sears_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('short_about', models.TextField(default='')),
                ('brand', models.CharField(max_length=200)),
                ('sears_link', models.URLField()),
                ('category', models.ManyToManyField(blank=True, related_name='products', to='products.category')),
            ],
        ),
    ]
