# Generated by Django 5.0 on 2024-01-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sears_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('short_about', models.TextField(default='')),
                ('brand', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('sears_link', models.URLField()),
            ],
        ),
    ]
