services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A my_products worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
