# this file is not configurated right, please use:
#   python manage.py runserver 0.0.0.0:8000
#   docker run -d --hostname my-rabbit --name some-rabbit -p 5672:5672 -p 8080:15672 rabbitmq:3-management
#   celery -A my_products worker -l info

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  celery:
    build: .
    command: celery -A my_products worker -l info
    volumes:
      - .:/code
    depends_on:
      - web
      - rabbitmq

networks:
  rabbitmq_go_net:
    driver: bridge